# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김은서
title: Backend Developer
email: eunseokim43@gmail.com
website: github.com/ES-Im
blog:  silver-w.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  ES-Im

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://velog.io/@gehwan96

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
    안녕하세요.  <br>
    
    <br>
  
    <strong>기술 스택<strong>
      - 프레임워크 - <mark>Spring Boot</mark>
      - 언어 - <mark>Java 21</mark>, <mark>Java Script</mark>
      - 테스트 - <mark></mark>
      - 미들웨어 - <mark></mark>
      - 웹서버 - <mark></mark>
      - DB(Hibernate) - <mark>MySQL</mark>,<mark>Mybatis</mark>, <mark>JPA</mark>, <mark>QueryDSL</mark>
      - 기타 - <mark></mark>, <mark></mark>, <mark>Github</mark>

content:
  - title: 경력
    layout: list
    content:
      - layout: left
        title: 인천광역시
        link: 
        sub_title: 
        caption: 2021.09 ~ 2024.08
        description: | # this will include new lines to allow paragraphs
          21년 4월 지방공무원 공개경쟁임용시험을 통해 인천광역시에 소속되어 행정 업무와 민원 업무 등 각종 업무를 수행하였습니다.
          <br>
          
          <strong>주요 업무<strong>
          - 2022년-2023년 행정안전부 세외수입 결산 및 예산 보고 및 사용자 교육
                          세외수입 프로그램 총괄 관리 업무 
          - 2024년        LH(한국토지주택공사) 인천지역본부와 협업, 2024년 부동산가격공시 결정 및 공시 업무
content:
  - title: 학력 # Title for the section
    layout: list # Layout for the section
    content:
      - title: 인하공업전문대학
        caption: 전문통신공학과
        sub_title: 2025.02 ~ 현재
        description: | # this will include new lines to allow paragraphs
          
      - title: 동양대학교
        caption: 행정학부
        sub_title: 2012.03 - 2014.12
        description: | # this will include new lines to allow paragraphs
          - 5급 고시 장학생 입학, 전액 장학금 수여
          - 3학년 2학기 후 중퇴

      - title: 영광여자고등학교
        caption: 인문계열
        sub_title: 2009.03 - 2012.02
        description: | # this will include new lines to allow paragraphs
          경상북도 영주 소재 고등학교  
          
- title: 자격
    layout: list
    content:
      - layout: left
        title: 
        link: 
        sub_title: 
        caption: 2021.09 ~ 2024.08
        description: | # this will include new lines to allow paragraphs
          

## Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
